<a href="https://colab.research.google.com/github/Snehanjaliuppu/AIML-2025/blob/main/PnS1_1305.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Numpy Library

In [1]:
import numpy as np

Create an Array

In [2]:
a=[1,2,34,6,32,14,65,7]
arr=np.array(a)
print(arr)

[ 1  2 34  6 32 14 65  7]


In [3]:
arr=np.array([1,2,34,6,32,14,65,7])
print(arr)

[ 1  2 34  6 32 14 65  7]


In [4]:
print(arr[0])
print(arr[2])

1
34


Create a 2D array(Matrix)

In [8]:
aa = [[1,2,3,4],[4,2,3,6]]  # Remove the extra brackets around the first list
A = np.array(aa)
print(A)

[[1 2 3 4]
 [4 2 3 6]]


In [10]:
A = np.array([[1,2,3,4],[4,2,3,6]])
print(A)

[[1 2 3 4]
 [4 2 3 6]]


In [11]:
print(type(A))

<class 'numpy.ndarray'>


In [12]:
print(type(arr))

<class 'numpy.ndarray'>


In [13]:
np.ndim(arr)

1

In [14]:
np.ndim(A)

2

Size of an array OR the number of elements in an array

In [15]:
print(np.size(arr))

8


In [16]:
print(np.size(A))

8


Shape of an array (m,n): m=number of rows and n=number of columns

In [17]:
print(np.shape(arr))

(8,)


In [18]:
print(np.shape(A))

(2, 4)


Rows and Columns of an Array

In [20]:
A = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(A)


[[1 2 3]
 [3 4 5]
 [4 5 6]]


Print the rows

In [21]:
print(A[0,:])
print(A[1,:])
print(A[2,:])

[1 2 3]
[3 4 5]
[4 5 6]


Print the Columns

In [22]:
print(A[:,0])
print(A[:,1])
print(A[:,2])

[1 3 4]
[2 4 5]
[3 5 6]


Print an element in a matrix

In [23]:
print(A[2,1])

5


Pandas Library

In [24]:
import pandas as pd

Craete a Dictionary

In [30]:
Dataset={
    "State": ['Andhra Pradesh','Maharashtra','Karantaka','Kerela','Tamil Nadu'],
    "Capital": ['Hyderabad','Mumbai','Benguluru','Trivandrum','Chennai'],
    "Literacy %": [89, 77, 82, 97, 85],
    "Avg High temp(c)": [33, 30, 29, 31, 32]}
print(Dataset)


{'State': ['Andhra Pradesh', 'Maharashtra', 'Karantaka', 'Kerela', 'Tamil Nadu'], 'Capital': ['Hyderabad', 'Mumbai', 'Benguluru', 'Trivandrum', 'Chennai'], 'Literacy %': [89, 77, 82, 97, 85], 'Avg High temp(c)': [33, 30, 29, 31, 32]}


Create a DataFrame of a dataset through Dictionary

In [31]:
df = pd.DataFrame(Dataset)
print(df)

            State     Capital  Literacy %  Avg High temp(c)
0  Andhra Pradesh   Hyderabad          89                33
1     Maharashtra      Mumbai          77                30
2       Karantaka   Benguluru          82                29
3          Kerela  Trivandrum          97                31
4      Tamil Nadu     Chennai          85                32


Print the first 2 entries of a dataset

In [32]:
print(df.head(2))

            State    Capital  Literacy %  Avg High temp(c)
0  Andhra Pradesh  Hyderabad          89                33
1     Maharashtra     Mumbai          77                30


Print the last 3 entries of a dataset

In [33]:
print(df.tail(3))

        State     Capital  Literacy %  Avg High temp(c)
2   Karantaka   Benguluru          82                29
3      Kerela  Trivandrum          97                31
4  Tamil Nadu     Chennai          85                32


Types of attributes of a dataset

In [34]:
print(df.dtypes)

State               object
Capital             object
Literacy %           int64
Avg High temp(c)     int64
dtype: object


In [35]:
print(df.sort_values('Literacy %', ascending=False))

            State     Capital  Literacy %  Avg High temp(c)
3          Kerela  Trivandrum          97                31
0  Andhra Pradesh   Hyderabad          89                33
4      Tamil Nadu     Chennai          85                32
2       Karantaka   Benguluru          82                29
1     Maharashtra      Mumbai          77                30


Slicing two or more columns with its attribute names

In [37]:
print(df[['State', 'Capital']])

            State     Capital
0  Andhra Pradesh   Hyderabad
1     Maharashtra      Mumbai
2       Karantaka   Benguluru
3          Kerela  Trivandrum
4      Tamil Nadu     Chennai


Locating the 2nd row through label

In [38]:
print(df.loc[2])

State               Karantaka
Capital             Benguluru
Literacy %                 82
Avg High temp(c)           29
Name: 2, dtype: object


Locating the 2nd row through index

In [39]:
print(df.iloc[2])

State               Karantaka
Capital             Benguluru
Literacy %                 82
Avg High temp(c)           29
Name: 2, dtype: object


Display a particular element through indexs of row and column

In [40]:
print(df.loc[1, 'Literacy %'])

77


Display a particular element through labels of row and column

In [41]:
print(df.loc[1, 'Literacy %'])

77
